AllCops:
  Exclude:
  - 'bin/*'
  - 'app/lib/*'
  - 'app/channels/**/*'
  - 'spec/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/LineLength:
  Max: 80
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Metrics/PerceivedComplexity:
  Max: 5

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
